name: SSH into EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 54.243.13.32
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Run commands on the EC2 instance
            echo "Hello, EC2 instance!"
            # Add more commands as needed
