name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          sudo docker build -t my-app .
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > keypair.pem 
          chmod 400 keypair.pem
          sudo docker save my-app | ssh -i keypair.pem ubuntu@54.243.13.32 "docker load"

      - name: SSH into EC2 instance and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: 3.83.148.215
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run -d -p 8081:8081 my-app
