name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_ID }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY_ID }} ubuntu@ec2-107-20-26-129.compute-1.amazonaws.com 'git clone https://github.com/Atifkarim121/newgithubaction121.git'
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY_ID }} ubuntu@ec2-107-20-26-129.compute-1.amazonaws.com 'docker build -t java:latest .'
          #ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY_ID }} ubuntu@ec2-107-20-26-129.compute-1.amazonaws.com 'docker run -dp 8081:8081 java:latest'
