name: SSH into EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 54.82.46.229
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Add your SSH commands or scripts here if needed

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone repository
        run: git clone https://github.com/Atifkarim121/newgithubaction121.git

      - name: Build Docker image
        run: docker build -t my-app1 .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 my-app1
